# Generated by Django 5.0.1 on 2026-09-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presence", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deepworksession",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
